/// 80 classes COCO standard (YOLOv8n).
abstract final class CocoClasses {
  static const count = 80;

  static const keys = <String>[
    'person',
    'bicycle',
    'car',
    'motorcycle',
    'airplane',
    'bus',
    'train',
    'truck',
    'boat',
    'traffic_light',
    'fire_hydrant',
    'stop_sign',
    'parking_meter',
    'bench',
    'bird',
    'cat',
    'dog',
    'horse',
    'sheep',
    'cow',
    'elephant',
    'bear',
    'zebra',
    'giraffe',
    'backpack',
    'umbrella',
    'handbag',
    'tie',
    'suitcase',
    'frisbee',
    'skis',
    'snowboard',
    'sports_ball',
    'kite',
    'baseball_bat',
    'baseball_glove',
    'skateboard',
    'surfboard',
    'tennis_racket',
    'bottle',
    'wine_glass',
    'cup',
    'fork',
    'knife',
    'spoon',
    'bowl',
    'banana',
    'apple',
    'sandwich',
    'orange',
    'broccoli',
    'carrot',
    'hot_dog',
    'pizza',
    'donut',
    'cake',
    'chair',
    'couch',
    'potted_plant',
    'bed',
    'dining_table',
    'toilet',
    'tv',
    'laptop',
    'mouse',
    'remote',
    'keyboard',
    'cell_phone',
    'microwave',
    'oven',
    'toaster',
    'sink',
    'refrigerator',
    'book',
    'clock',
    'vase',
    'scissors',
    'teddy_bear',
    'hair_drier',
    'toothbrush',
  ];

  static const frenchLabels = <String, String>{
    'person': 'Personne',
    'bicycle': 'Velo',
    'car': 'Voiture',
    'motorcycle': 'Moto',
    'airplane': 'Avion',
    'bus': 'Bus',
    'train': 'Train',
    'truck': 'Camion',
    'boat': 'Bateau',
    'traffic_light': 'Feu tricolore',
    'fire_hydrant': 'Borne incendie',
    'stop_sign': 'Stop',
    'parking_meter': 'Parcmètre',
    'bench': 'Banc',
    'bird': 'Oiseau',
    'cat': 'Chat',
    'dog': 'Chien',
    'horse': 'Cheval',
    'sheep': 'Mouton',
    'cow': 'Vache',
    'elephant': 'Elephant',
    'bear': 'Ours',
    'zebra': 'Zebre',
    'giraffe': 'Girafe',
    'backpack': 'Sac a dos',
    'umbrella': 'Parapluie',
    'handbag': 'Sac a main',
    'tie': 'Cravate',
    'suitcase': 'Valise',
    'frisbee': 'Frisbee',
    'skis': 'Skis',
    'snowboard': 'Snowboard',
    'sports_ball': 'Ballon',
    'kite': 'Cerf-volant',
    'baseball_bat': 'Batte de baseball',
    'baseball_glove': 'Gant de baseball',
    'skateboard': 'Skateboard',
    'surfboard': 'Planche de surf',
    'tennis_racket': 'Raquette de tennis',
    'bottle': 'Bouteille',
    'wine_glass': 'Verre a vin',
    'cup': 'Tasse',
    'fork': 'Fourchette',
    'knife': 'Couteau',
    'spoon': 'Cuillere',
    'bowl': 'Bol',
    'banana': 'Banane',
    'apple': 'Pomme',
    'sandwich': 'Sandwich',
    'orange': 'Orange',
    'broccoli': 'Brocoli',
    'carrot': 'Carotte',
    'hot_dog': 'Hot-dog',
    'pizza': 'Pizza',
    'donut': 'Donut',
    'cake': 'Gateau',
    'chair': 'Chaise',
    'couch': 'Canape',
    'potted_plant': 'Plante en pot',
    'bed': 'Lit',
    'dining_table': 'Table',
    'toilet': 'Toilettes',
    'tv': 'Television',
    'laptop': 'Ordinateur portable',
    'mouse': 'Souris',
    'remote': 'Telecommande',
    'keyboard': 'Clavier',
    'cell_phone': 'Telephone',
    'microwave': 'Micro-ondes',
    'oven': 'Four',
    'toaster': 'Grille-pain',
    'sink': 'Evier',
    'refrigerator': 'Refrigerateur',
    'book': 'Livre',
    'clock': 'Horloge',
    'vase': 'Vase',
    'scissors': 'Ciseaux',
    'teddy_bear': 'Peluche',
    'hair_drier': 'Seche-cheveux',
    'toothbrush': 'Brosse a dents',
  };

  static const vehicles = {
    'car',
    'bus',
    'truck',
    'train',
    'bicycle',
    'motorcycle',
    'airplane',
    'boat',
  };

  static const dangers = {
    'stop_sign',
    'traffic_light',
    'fire_hydrant',
    'parking_meter',
  };

  static const animals = {
    'bird',
    'cat',
    'dog',
    'horse',
    'sheep',
    'cow',
    'elephant',
    'bear',
    'zebra',
    'giraffe',
  };

  static String keyForId(int id) => (id >= 0 && id < keys.length) ? keys[id] : 'unknown';

  static String labelFr(String key) => frenchLabels[key] ?? key;
}
