import 'package:flutter/material.dart';

import 'coco_classes.dart';

abstract final class NavisConstants {
  static Map<String, String> get frenchLabels => CocoClasses.frenchLabels;

  static final classIcons = <String, IconData>{
    'person': Icons.person_rounded,
    'bicycle': Icons.pedal_bike_rounded,
    'car': Icons.directions_car_rounded,
    'motorcycle': Icons.two_wheeler_rounded,
    'airplane': Icons.flight_rounded,
    'bus': Icons.directions_bus_rounded,
    'train': Icons.train_rounded,
    'truck': Icons.local_shipping_rounded,
    'boat': Icons.directions_boat_rounded,
    'traffic_light': Icons.traffic_rounded,
    'stop_sign': Icons.stop_circle_rounded,
    'fire_hydrant': Icons.water_drop_rounded,
    'parking_meter': Icons.local_parking_rounded,
    'bench': Icons.weekend_rounded,
    'bird': Icons.flutter_dash_rounded,
    'cat': Icons.pets_rounded,
    'dog': Icons.pets_rounded,
    'horse': Icons.pets_rounded,
    'sheep': Icons.pets_rounded,
    'cow': Icons.pets_rounded,
    'elephant': Icons.pets_rounded,
    'bear': Icons.pets_rounded,
    'zebra': Icons.pets_rounded,
    'giraffe': Icons.pets_rounded,
    'backpack': Icons.backpack_rounded,
    'umbrella': Icons.beach_access_rounded,
    'handbag': Icons.shopping_bag_rounded,
    'tie': Icons.checkroom_rounded,
    'suitcase': Icons.luggage_rounded,
    'bottle': Icons.local_drink_rounded,
    'wine_glass': Icons.wine_bar_rounded,
    'cup': Icons.coffee_rounded,
    'fork': Icons.restaurant_rounded,
    'knife': Icons.restaurant_rounded,
    'spoon': Icons.restaurant_rounded,
    'bowl': Icons.ramen_dining_rounded,
    'banana': Icons.eco_rounded,
    'apple': Icons.eco_rounded,
    'sandwich': Icons.lunch_dining_rounded,
    'orange': Icons.eco_rounded,
    'broccoli': Icons.eco_rounded,
    'carrot': Icons.eco_rounded,
    'hot_dog': Icons.lunch_dining_rounded,
    'pizza': Icons.local_pizza_rounded,
    'donut': Icons.cake_rounded,
    'cake': Icons.cake_rounded,
    'chair': Icons.chair_rounded,
    'couch': Icons.weekend_rounded,
    'potted_plant': Icons.local_florist_rounded,
    'bed': Icons.bed_rounded,
    'dining_table': Icons.table_restaurant_rounded,
    'toilet': Icons.wc_rounded,
    'tv': Icons.tv_rounded,
    'laptop': Icons.laptop_rounded,
    'mouse': Icons.mouse_rounded,
    'remote': Icons.settings_remote_rounded,
    'keyboard': Icons.keyboard_rounded,
    'cell_phone': Icons.smartphone_rounded,
    'microwave': Icons.microwave_rounded,
    'oven': Icons.countertops_rounded,
    'toaster': Icons.breakfast_dining_rounded,
    'sink': Icons.water_rounded,
    'refrigerator': Icons.kitchen_rounded,
    'book': Icons.menu_book_rounded,
    'clock': Icons.schedule_rounded,
    'vase': Icons.local_florist_rounded,
    'scissors': Icons.content_cut_rounded,
    'teddy_bear': Icons.toys_rounded,
    'hair_drier': Icons.dry_rounded,
    'toothbrush': Icons.clean_hands_rounded,
  };
}
